import vue from 'eslint-plugin-vue'
import globals from 'globals'

export default [
    {
        ignores: [
            'node_modules/**',
            'public/build/**',
            'public/boneyard/**',
            'coverage/**',
        ],
    },
    ...vue.configs['flat/base'],
    {
        files: ['resources/js/**/*.{js,vue}', 'tests/e2e/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.node,
                bootstrap: 'readonly',
                modalHidden: 'readonly',
                moneyFormat: 'readonly',
                showMessage: 'readonly',
                Swal: 'readonly',
            },
        },
        rules: {
            'constructor-super': 'error',
            'for-direction': 'error',
            'getter-return': 'error',
            'no-async-promise-executor': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-ex-assign': 'error',
            'no-import-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-loss-of-precision': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-obj-calls': 'error',
            'no-self-assign': 'error',
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-this-before-super': 'error',
            'no-undef': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-useless-backreference': 'error',
            'no-with': 'error',
            'require-yield': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'vue/no-duplicate-attributes': 'error',
            'vue/no-dupe-keys': 'error',
            'vue/no-parsing-error': 'error',
            'vue/no-reserved-component-names': 'error',
            'vue/no-shared-component-data': 'error',
            'vue/no-template-key': 'error',
            'vue/no-textarea-mustache': 'error',
            'vue/no-use-v-if-with-v-for': 'error',
            'vue/valid-v-bind': 'error',
            'vue/valid-v-for': 'error',
            'vue/valid-v-if': 'error',
            'vue/valid-v-else-if': 'error',
        },
    },
]
