ALTER TABLE payments
  MODIFY COLUMN enrollment TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN january TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN february TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN march TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN april TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN may TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN june TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN july TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN august TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN september TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN october TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN november TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN december TINYINT UNSIGNED NOT NULL DEFAULT 0;
