<?php

return [
    'KEY_WEEKS' => [
        'Lunes' => 'Lunes',
        'Martes' => 'Martes',
        'Miércoles' => 'Miércoles',
        'Jueves' => 'Jueves',
        'Viernes' => 'Viernes',
        'Sábados' => 'Sábado',
        'Domingos' => 'Domingo'
    ],
    'KEY_WEEKS_INDEX' => [
        1 => 'Lunes',
        2 => 'Martes',
        3 => 'Miércoles',
        4 => 'Jueves',
        5 => 'Viernes',
        6 => 'Sábado',
        7 => 'Domingo'
    ],
    'KEY_ASSIST_LETTER' => [
        'as' => 'X',
        'fa' => 'F',
        'ex' => 'E',
        're' => 'R',
        'in' => 'I',
    ],
    'KEY_ASSIST' => [
        'as' => 'Asistencia',
        'fa' => 'Falta',
        'ex' => 'Excusa',
        're' => 'Retiro',
        'in' => 'Incapacidad',
    ],
    'KEY_MONTHS' => [
        'Enero' => 'Enero', 'Febrero' => 'Febrero', 'Marzo' => 'Marzo',
        'Abril' => 'Abril', 'Mayo' => 'Mayo', 'Junio' => 'Junio',
        'Julio' => 'Julio', 'Agosto' => 'Agosto', 'Septiembre' => 'Septiembre',
        'Octubre' => 'Octubre', 'Noviembre' => 'Noviembre', 'Diciembre' => 'Diciembre',
    ],
    'KEY_MONTHS_INDEX' => [
        1 => 'Enero',
        2 => 'Febrero',
        3 => 'Marzo',
        4 => 'Abril',
        5 => 'Mayo',
        6 => 'Junio',
        7 => 'Julio',
        8 => 'Agosto',
        9 => 'Septiembre',
        10 => 'Octubre',
        11 => 'Noviembre',
        12 => 'Diciembre'
    ],
    'KEY_LABEL_MONTHS' => [
        'Enero', 'Febrero', 'Marzo',
        'Abril', 'Mayo', 'Junio',
        'Julio', 'Agosto', 'Septiembre',
        'Octubre', 'Noviembre', 'Diciembre',
    ],
    'KEY_INDEX_MONTHS' => [
        1 => 'january',
        2 => 'february',
        3 => 'march',
        4 => 'april',
        5 => 'may',
        6 => 'june',
        7 => 'july',
        8 => 'august',
        9 => 'september',
        10 => 'october',
        11 => 'november',
        12 => 'december'
    ],
    'KEY_INDEX_MONTHS_LABEL' => [
        'january' => 'Enero',
        'february' => 'Febrero',
        'march' => 'Marzo',
        'april' => 'Abril',
        'may' => 'Mayo',
        'june' => 'Junio',
        'july' => 'Julio',
        'august' => 'Agosto',
        'september' => 'Septiembre',
        'october' => 'Octubre',
        'november' => 'Noviembre',
        'december' => 'Diciembre',
    ],
    'KEY_GENDERS' => [
        'M' => 'Masculino',
        'F' => 'Femenino'
    ],
    'KEY_POSITIONS' => [
        'Portero' => 'Portero',
        'Defensa(Central)' => 'Defensa(Central)',
        'Defensa(Derecho)(Izquierdo)' => 'Defensa(Derecho)(Izquierdo)',
        'Volante(Central)' => 'Volante(Central)',
        'Volante(Primera linea)' => 'Volante(Primera linea)',
        'Volante(Segunda linea)' => 'Volante(Segunda linea)',
        'Volante(Extremo)' => 'Volante(Extremo)',
        'Delantero' => 'Delantero',
    ],
    'KEY_BLOOD_TYPES' => [
        'O-' => 'O-', 'O+' => 'O+',
        'A-' => 'A-', 'A+' => 'A+',
        'B-' => 'B-', 'B+' => 'B+',
        'AB-' => 'AB-', 'AB+' => 'AB+',
    ],
    'KEY_AVERAGES' => [
        'Bajo' => 'Bajo',
        'Medio' => 'Medio',
        'Alto' => 'Alto',
        'Superior' => 'Superior',
    ],
    'KEY_DOMINANT_PROFILE' => [
        'DIESTRO' => 'DIESTRO',
        'ZURDO' => 'ZURDO',
        'AMBIDIESTRO' => 'AMBIDIESTRO',
    ],
    'KEY_PAYMENTS_SELECT' => [
        '0' => "Pendiente",
        '1' => "Pagó",
        '9' => "Pagó - Efectivo",
        '10' => "Pagó - Consignación",
        '11' => "Pago Anualidad Consignación",
        '12' => "Pago Anualidad Efectivo",
        '13' => "Acuerdo de Pago",
        '14' => "No Aplica",
        '2' => "Debe",
        '3' => "Abonó",
        '4' => "Incapacidad",
        '5' => "Retiro Temporal",
        '6' => "Retiro Definitivo",
        '7' => "Otro",
        '8' => "Becado",
    ],

    'KEY_RELATIONSHIPS_SELECT' => [
        0 => 'DESCONOCIDO',
        1 => 'ABUELA',
        2 => 'ABUELO',
        3 => 'AMIGA',
        4 => 'AMIGO',
        5 => 'BISABEULA',
        6 => 'BISABUELO',
        7 => 'COMADRE',
        8 => 'CUÑADA',
        9 => 'CUÑADO',
        10 => 'FAMILIAR',
        11 => 'HERMANA',
        12 => 'HERMANO',
        13 => 'MADRASTRA',
        14 => 'MADRINA',
        15 => 'MAMA',
        16 => 'MAMA ADOPTIVA',
        17 => 'PADRASTRO',
        18 => 'PADRE DE CRIANZA',
        19 => 'PADRINO',
        20 => 'PAPA',
        21 => 'PAPA ADOPTIVO',
        22 => 'PRIMA',
        23 => 'PRIMO',
        24 => 'SOBRINA',
        25 => 'SOBRINO',
        26 => 'TIA',
        27 => 'TIO',
        28 => 'VECINA',
        29 => 'COMAMÁ',
        30 => 'ACUDIENTE'
    ],

    'KEY_POSITIONS_ASSIGNED' => [
        'ENTRENADOR(A)' => 'ENTRENADOR(A)',
        'PRACTICANTE' => 'PRACTICANTE',
        'DIRECCIÓN GENERAL' => 'DIRECCIÓN GENERAL',
        'ADMINISTRADOR(A)' => 'ADMINISTRADOR(A)',
        'COORDINADOR(A)' => 'COORDINADOR(A)',
        'PSICÓLOGO' => 'PSICÓLOGO',
        'FISIOTERAPEUTA' => 'FISIOTERAPEUTA',
        'CONTADOR(A)' => 'CONTADOR(A)',
        'MÉDICO' => 'MÉDICO',
    ]

];
