<?php

return [
    'KEY_WEEKS' => [
        'Lunes' => 'Lunes',
        'Martes' => 'Martes',
        'Miércoles' => 'Miércoles',
        'Jueves' => 'Jueves',
        'Viernes' => 'Viernes',
        'Sábado' => 'Sábado',
        'Domingos' => 'Domingo',
    ],
    'KEY_WEEKS_INDEX' => [
        1 => 'Lunes',
        2 => 'Martes',
        3 => 'Miércoles',
        4 => 'Jueves',
        5 => 'Viernes',
        6 => 'Sábado',
        7 => 'Domingo',
    ],
    'KEY_ASSIST_LETTER' => [
        1 => '&#10003;',
        2 => '&#10008;',
        3 => 'E',
        4 => 'R',
        5 => 'I',
    ],
    'KEY_ASSIST' => [
        1 => 'Asistencia',
        2 => 'Falta',
        3 => 'Excusa',
        4 => 'Retiro',
        5 => 'Incapacidad',
    ],
    'KEY_ASSIST_EXCEL' => [
        1 => 'X',
        2 => 'F',
        3 => 'E',
        4 => 'R',
        5 => 'I',
    ],
    'KEY_MONTHS' => [
        'Enero' => 'Enero', 'Febrero' => 'Febrero', 'Marzo' => 'Marzo',
        'Abril' => 'Abril', 'Mayo' => 'Mayo', 'Junio' => 'Junio',
        'Julio' => 'Julio', 'Agosto' => 'Agosto', 'Septiembre' => 'Septiembre',
        'Octubre' => 'Octubre', 'Noviembre' => 'Noviembre', 'Diciembre' => 'Diciembre',
    ],
    'KEY_MONTHS_INDEX' => [
        1 => 'Enero',
        2 => 'Febrero',
        3 => 'Marzo',
        4 => 'Abril',
        5 => 'Mayo',
        6 => 'Junio',
        7 => 'Julio',
        8 => 'Agosto',
        9 => 'Septiembre',
        10 => 'Octubre',
        11 => 'Noviembre',
        12 => 'Diciembre',
    ],
    'KEY_LABEL_MONTHS' => [
        'Enero', 'Febrero', 'Marzo',
        'Abril', 'Mayo', 'Junio',
        'Julio', 'Agosto', 'Septiembre',
        'Octubre', 'Noviembre', 'Diciembre',
    ],
    'KEY_INDEX_MONTHS' => [
        1 => 'january',
        2 => 'february',
        3 => 'march',
        4 => 'april',
        5 => 'may',
        6 => 'june',
        7 => 'july',
        8 => 'august',
        9 => 'september',
        10 => 'october',
        11 => 'november',
        12 => 'december',
    ],
    'KEY_INDEX_MONTHS_LABEL' => [
        'january' => 'Enero',
        'february' => 'Febrero',
        'march' => 'Marzo',
        'april' => 'Abril',
        'may' => 'Mayo',
        'june' => 'Junio',
        'july' => 'Julio',
        'august' => 'Agosto',
        'september' => 'Septiembre',
        'october' => 'Octubre',
        'november' => 'Noviembre',
        'december' => 'Diciembre',
    ],
    'KEY_GENDERS' => [
        'M' => 'Masculino',
        'F' => 'Femenino',
    ],
    'KEY_POSITIONS' => [
        'Portero' => 'Portero',
        'Defensa (Central)' => 'Defensa (Central)',
        'Defensa (Derecho)(Izquierdo)' => 'Defensa (Derecho)(Izquierdo)',
        'Defensa (Izquierdo)' => 'Defensa (Izquierdo)',
        'Defensa (Derecho)' => 'Defensa (Derecho)',
        'Defensa' => 'Defensa',
        'Volante (Defensivo Izquierdo)' => 'Volante (Defensivo Izquierdo)',
        'Volante (Defensivo Derecho)' => 'Volante (Defensivo Derecho)',
        'Volante (Defensivo Central)' => 'Volante (Defensivo Central)',
        'Volante (Ofensivo Izquierdo)' => 'Volante (Ofensivo Izquierdo)',
        'Volante (Ofensivo Derecho)' => 'Volante (Ofensivo Derecho)',
        'Volante (Ofensivo Central)' => 'Volante (Ofensivo Central)',
        'Volante (Extremo Izquierdo)' => 'Volante (Extremo Izquierdo)',
        'Volante (Extremo Derecho)' => 'Volante (Extremo Derecho)',
        'Volante (Primera línea)' => 'Volante (Primera línea)',
        'Volante (Segunda línea)' => 'Volante (Segunda línea)',
        'Volante (Primera linea)' => 'Volante (Primera linea)',
        'Volante (Segunda linea)' => 'Volante (Segunda linea)',
        'Volante (Extremo)' => 'Volante (Extremo)',
        'Volante (Central)' => 'Volante (Central)',
        'Delantero (Izquierdo)' => 'Delantero (Izquierdo)',
        'Delantero (Derecho)' => 'Delantero (Derecho)',
        'Delantero (Central)' => 'Delantero (Central)',
        'Delantero' => 'Delantero',
    ],
    'KEY_POSITIONS_HIDDEN_FROM_SELECT' => [
        'Defensa (Derecho)(Izquierdo)' => 'Defensa (Derecho)(Izquierdo)',
        'Volante (Primera linea)' => 'Volante (Primera linea)',
        'Volante (Segunda linea)' => 'Volante (Segunda linea)',
        'Volante (Extremo)' => 'Volante (Extremo)',
        'Delantero' => 'Delantero',
    ],
    'KEY_BLOOD_TYPES' => [
        'O-' => 'O-', 'O+' => 'O+',
        'A-' => 'A-', 'A+' => 'A+',
        'B-' => 'B-', 'B+' => 'B+',
        'AB-' => 'AB-', 'AB+' => 'AB+',
    ],
    'KEY_AVERAGES' => [
        'Bajo' => 'Bajo',
        'Medio' => 'Medio',
        'Alto' => 'Alto',
        'Superior' => 'Superior',
    ],
    'KEY_DOMINANT_PROFILE' => [
        'DIESTRO' => 'DIESTRO',
        'ZURDO' => 'ZURDO',
        'AMBIDIESTRO' => 'AMBIDIESTRO',
    ],
    'KEY_PAYMENTS_SELECT' => [
        0 => 'Pendiente',
        1 => 'Pagó',
        9 => 'Pagó - Efectivo',
        10 => 'Pagó - Consignación',
        11 => 'Pagó A. Consignación',
        12 => 'Pagó A. Efectivo',
        13 => 'Acuerdo de Pago',
        14 => 'No Aplica',
        15 => 'Pagó - Saldo a favor',
        2 => 'Debe',
        3 => 'Abonó',
        4 => 'Incapacidad',
        5 => 'Retiro Temporal',
        6 => 'Retiro Definitivo',
        7 => 'Otro',
        8 => 'Becado',
    ],

    'KEY_RELATIONSHIPS_SELECT' => [
        15 => 'MADRE',
        20 => 'PADRE',
        1 => 'ABUELA',
        2 => 'ABUELO',
        11 => 'HERMANA',
        12 => 'HERMANO',
        26 => 'TÍA',
        27 => 'TÍO',
        10 => 'OTRO FAMILIAR',
        30 => 'ACUDIENTE',
    ],

    // Se conservan únicamente para mostrar correctamente registros históricos.
    'KEY_RELATIONSHIPS_LEGACY' => [
        3 => 'AMIGA',
        4 => 'AMIGO',
        5 => 'BISABUELA',
        6 => 'BISABUELO',
        7 => 'COMADRE',
        8 => 'CUÑADA',
        9 => 'CUÑADO',
        13 => 'MADRASTRA',
        14 => 'MADRINA',
        16 => 'MADRE ADOPTIVA',
        17 => 'PADRASTRO',
        18 => 'PADRE DE CRIANZA',
        19 => 'PADRINO',
        21 => 'PADRE ADOPTIVO',
        22 => 'PRIMA',
        23 => 'PRIMO',
        24 => 'SOBRINA',
        25 => 'SOBRINO',
        28 => 'VECINA',
        29 => 'COMAMÁ',
    ],

    'KEY_RELATIONSHIPS_ALIASES' => [
        'MAMA' => 15,
        'MAMÁ' => 15,
        'PAPA' => 20,
        'PAPÁ' => 20,
        'TIA' => 26,
        'TIO' => 27,
        'FAMILIAR' => 10,
    ],

    'KEY_POSITIONS_ASSIGNED' => [
        'ENTRENADOR(A)' => 'ENTRENADOR(A)',
        'PRACTICANTE' => 'PRACTICANTE',
        'DIRECCIÓN GENERAL' => 'DIRECCIÓN GENERAL',
        'ADMINISTRADOR(A)' => 'ADMINISTRADOR(A)',
        'COORDINADOR(A)' => 'COORDINADOR(A)',
        'PSICÓLOGO' => 'PSICÓLOGO',
        'FISIOTERAPEUTA' => 'FISIOTERAPEUTA',
        'CONTADOR(A)' => 'CONTADOR(A)',
        'MÉDICO' => 'MÉDICO',
    ],

    'KEY_TRAINING_SESSION_GENERAL_OBJECTIVE' => [
        'ABP' => 'ABP',
        'ATAQUE ORGANIZADO' => 'ATAQUE ORGANIZADO',
        'DEFENSA ORGANIZADA' => 'DEFENSA ORGANIZADA',
        'TRANSICIONES DEFENSIVAS' => 'TRANSICIONES DEFENSIVAS',
        'TRANSICIONES OFENSIVAS' => 'TRANSICIONES OFENSIVAS',
    ],
    'KEY_TRAINING_SESSION_SPECIFIC_GOAL' => [
        'COMPORTAMIENTO TRAS RECUPERACIÓN' => 'COMPORTAMIENTO TRAS RECUPERACIÓN',
        'CREACIÓN DE JUEGO' => 'CREACIÓN DE JUEGO',
        'DEFENDER FINALIZACIÓN' => 'DEFENDER FINALIZACIÓN',
        'EVITAR CREACIÓN' => 'EVITAR CREACIÓN',
        'FINALIZACIÓN' => 'FINALIZACIÓN',
        'PRESIÓN SALIDA' => 'PRESIÓN SALIDA',
        'PRESIÓN TRAS PÉRDIDA' => 'PRESIÓN TRAS PÉRDIDA',
        'SALIDA DE BALÓN' => 'SALIDA DE BALÓN',
    ],
    'KEY_TRAINING_SESSION_CONTENT' => [
        'AMPLITUD' => 'AMPLITUD',
        'ANTICIPACIÓN' => 'ANTICIPACIÓN',
        'APOYOS AL POSEEDOR' => 'APOYOS AL POSEEDOR',
        'CAMBIO DE ORIENTACIÓN' => 'CAMBIO DE ORIENTACIÓN',
        'COBERTURA/PERMUTA' => 'COBERTURA/PERMUTA',
        'CONDUCCIÓN' => 'CONDUCCIÓN',
        'CONTROL' => 'CONTROL',
        'CÓRNER DEFENSIVO' => 'CÓRNER DEFENSIVO',
        'CÓRNER OFENSIVO' => 'CÓRNER OFENSIVO',
        'DESMARQUE DE APOYO' => 'DESMARQUE DE APOYO',
        'DESMARQUE DE RUPTURA' => 'DESMARQUE DE RUPTURA',
        'DESPEJE' => 'DESPEJE',
        'ENTRADA' => 'ENTRADA',
        'ESTRUCTURA Y MOVIMIENTOS EN ATAQUE' => 'ESTRUCTURA Y MOVIMIENTOS EN ATAQUE',
        'ESTRUCTURA Y MOVIMIENTOS SALIDA' => 'ESTRUCTURA Y MOVIMIENTOS SALIDA',
        'FALTAS FRONTALES' => 'FALTAS FRONTALES',
        'FALTAS LATERALES DEFENSIVAS' => 'FALTAS LATERALES DEFENSIVAS',
        'FALTAS LATERALES OFENSIVAS' => 'FALTAS LATERALES OFENSIVAS',
        'JUGAR ENTRE LÍNEAS' => 'JUGAR ENTRE LÍNEAS',
        'MARCAJE INDIVIDUAL' => 'MARCAJE INDIVIDUAL',
        'MARCAJE ZONAL' => 'MARCAJE ZONAL',
        'OCUPACIÓN ZONAS REMATE' => 'OCUPACIÓN ZONAS REMATE',
        'PASE' => 'PASE',
        'PRESIÓN COLECTIVA' => 'PRESIÓN COLECTIVA',
        'PRESIÓN INDIVIDUAL' => 'PRESIÓN INDIVIDUAL',
        'PRIORIDADES DEL POSSEDOR (RECUP.)' => 'PRIORIDADES DEL POSSEDOR (RECUP.)',
        'PROFUNDIDAD' => 'PROFUNDIDAD',
        'PROTECCIÓN' => 'PROTECCIÓN',
        'REGATE' => 'REGATE',
        'REMATE' => 'REMATE',
        'TEMPORIZACIÓN' => 'TEMPORIZACIÓN',
        'VIGILANCIA DEFENSIVA' => 'VIGILANCIA DEFENSIVA',
        'VIGILANCIA OFENSIVA' => 'VIGILANCIA OFENSIVA',
    ],
    'KEY_TRAINING_SESSION_TASKS' => [
        'AUTOMATISMOS' => 'AUTOMATISMOS',
        'CIRCUITO FÍSICO' => 'CIRCUITO FÍSICO',
        'CONSERVACIÓN' => 'CONSERVACIÓN',
        'JUEGO DE POSICIÓN' => 'JUEGO DE POSICIÓN',
        'OLEADAS' => 'OLEADAS',
        'PARTIDO CONDICIONADO' => 'PARTIDO CONDICIONADO',
        'PARTIDO ESPACIO REDUCIDO' => 'PARTIDO ESPACIO REDUCIDO',
        'TÉCNICA ANALÍTICA' => 'TÉCNICA ANALÍTICA',
    ],
    'KEY_DOCUMENT_TYPES' => [
        'Registro Civil' => 'Registro Civil',
        'Tarjeta de Indentidad' => 'Tarjeta de Indentidad',
        'Otro Documento' => 'Otro Documento',
    ],

    'KEY_JORNADA' => [
        'Mañana' => 'Mañana',
        'Tarde' => 'Tarde',
    ],

    'UNIFORM_REQUESTS_TYPES' => [
        'UNIFORM' => 'Uniforme',
        'BALL' => 'Balón',
        'SOCKS' => 'Medias',
        'SHOES' => 'Guayos',
        'SHORTS' => 'Pantaloneta',
        'JERSEY' => 'Camisa',
        'OTHER' => 'Otro',
    ],

];
