name: Repository to cPanel

on:
  push:
    branches: [ template ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🔨 Test and build project
        run: |
          npm install
          npm run test:vue
          npm run build

      - name: Deploy full project except build
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_TEST_SERVER }}
          username: ${{ secrets.FTP_TEST_USERNAME }}
          password: ${{ secrets.FTP_TEST_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            public/build/**
            public/build

      - name: Deploy build folder clean
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_TEST_SERVER }}
          username: ${{ secrets.FTP_TEST_USERNAME }}
          password: ${{ secrets.FTP_TEST_PASSWORD }}
          local-dir: ./public/build/
          server-dir: /public/build/
          dangerous-clean-slate: true
